### ISSUE TITLE
List cast to Tensor

### ISSUE THREAD

**Issue by dvVenuto** [fuyuan-li/tensorflow-RIMs#1]
I am receiving the error: 

Failed to convert object of type <class 'list'> to Tensor. Contents: [1, TensorShape([Dimension(6), Dimension(100)])]. Consider casting elements to a supported type.

When running the ipython notebook copying_task scripts and also in using your code in other implementations.

**Comment by fuyuan-li** [comment]
Thanks David. What is your tensorflow version?

**Comment by dvVenuto** [comment]
I am using 1.9.0 right now

**Comment by fuyuan-li** [comment]
My implementation and samples are for 2.0+. Is it possible to upgrade TF version?
I'm also happy to make this compatible to both 1.x and 2.x. Any ideas?

**Comment by dvVenuto** [comment]
I got it working with 1.14 so it seems to be a one off error.

**Comment by dvVenuto** [comment]
Upgraded to 2.2 and its working

**Comment by fuyuan-li** [comment]
Thanks, David! Yes I remembered some differences in syntax between TF1.x and TF2.x might cause this.
